/* ==========================================================================
   script.js — the running order and every word the film shows.
   GENERATED by tools/script-from-screenplay.js from design/screenplay.json.
   ========================================================================== */
(function (TSUKI) {
  'use strict';
  const C = TSUKI.C;
  TSUKI.SCRIPT = {
    title: {"ja":"月の出でたらむ夜は","sub":"〜十五夜摺〜","zh":"月出之夜 · 十五夜摺","en":"On Nights When the Moon Comes Out — A Fifteenth-Night Impression","reading":"つきのいでたらむよは　じゅうごやずり"},
    curtain: { columns: ["月の出でたらむ夜は","十五夜摺"] },
    posterT: 21,
    segments: [
      {
        id: "jo-surizome", title_ja: "序　摺り初め", title_zh: "序　初摺", duration: 14,
        shot: "A (being printed)",
        text: [
          {"t":7,"dur":9,"kind":"haiku","ja":["月の出でたらむ夜は"],"seal":false,"en":"On Nights When the Moon Comes Out — A Fifteenth-Night Impression","zh":"月出之夜 · 十五夜摺","position":"upper-right","x":1716,"y":74,"ink":"dark","size":36,"font":"brush"},
        ],
      },
      {
        id: "tsuki-no-de", title_ja: "一　月の出", title_zh: "一　月出", duration: 26,
        shot: "A",
        transition: {"type":"cut","dur":0},
        text: [
          {"t":10,"dur":8,"kind":"haiku","ja":["名月や","池をめぐりて","夜もすがら"],"author":"芭蕉","seal":"月","seal_style":"朱文","zh":"明月当空——绕着池塘走啊走，走了一整夜。","position":"upper-left","x":540,"y":70,"ink":"light","size":50},
        ],
      },
      {
        id: "kage-e-taketori", title_ja: "二　影絵・竹取", title_zh: "二　影绘·竹取", duration: 26,
        shot: "B",
        transition: {"type":"cut","dur":0},
        text: [
          {"t":19,"dur":6,"kind":"narration","ja":["月の顔見るは、","忌むこと"],"author":"竹取物語","seal":"月","seal_style":"朱文","zh":"“望月亮的脸，是不吉利的。”","position":"right","x":1690,"y":140,"ink":"light","size":36},
        ],
      },
      {
        id: "mizu-no-tsuki", title_ja: "三　水の月", title_zh: "三　水中月", duration: 24,
        shot: "C",
        transition: {"type":"cut","dur":0},
        text: [
          {"t":17,"dur":8.5,"kind":"haiku","ja":["掬ひたる","月こぼれけり","子の手より"],"author":"小夜","seal":"小夜","seal_style":"白文","zh":"舀起的月亮，从孩子的手心洒落了。","position":"upper-left","x":150,"y":50,"ink":"light","size":46},
        ],
      },
      {
        id: "tsuki-tenshin", title_ja: "四　月天心", title_zh: "四　月在中天", duration: 28,
        shot: "D, then tilt down to A",
        transition: {"type":"cut","dur":0},
        text: [
          {"t":10.2,"dur":7.6,"kind":"narration","ja":["万の人、月を見む毎に、","此の兎の事思ひいだすべし。"],"author":"今昔物語集","seal":"月","seal_style":"朱文","zh":"世上众人，每当望月，都该想起这只兔子。","position":"left","x":150,"y":110,"ink":"light","size":38},
          {"t":20,"dur":8,"kind":"haiku","ja":["月天心","貧しき町を","通りけり"],"author":"蕪村","seal":"月","seal_style":"朱文","zh":"月到天心——走过一条贫寒的小街。","position":"upper-right","x":1160,"y":50,"ink":"light","size":46},
        ],
      },
      {
        id: "ama-no-hagoromo", title_ja: "五　天の羽衣", title_zh: "五　天之羽衣", duration: 42,
        shot: "B, then A′",
        transition: {"type":"kasumi","dur":3,"rows":7,"color":C.gofun},
        text: [
          {"t":4.5,"dur":9,"kind":"letter","ja":["脱ぎおく衣を形見と見たまへ。","月の出でたらむ夜は、","見おこせたまへ。"],"author":"かぐや姫の文　竹取物語","seal":"月","seal_style":"朱文","zh":"请把留下的衣裳当作念想。有月亮出来的夜晚，请望向我。","position":"right","x":1660,"y":110,"ink":"light","size":40,"font":"brush"},
        ],
      },
      {
        id: "atozuri", title_ja: "六　後摺", title_zh: "六　后摺", duration: 30,
        shot: "A (後摺), A′ inserts, 月に雁 crop",
        transition: {"type":"cut","dur":0},
        text: [
          {"t":13.6,"dur":8,"kind":"kanshi","ja":["三五夜中新月色","二千里外故人心"],"author":"白居易","seal":"月","seal_style":"朱文","zh":"白居易《八月十五日夜禁中独直对月忆元九》","position":"left","x":440,"y":120,"ink":"dark","size":44,"chirashi":[0,0]},
        ],
      },
      {
        id: "ariake", title_ja: "七　有明", title_zh: "七　有明之月", duration: 16,
        shot: "B (後摺)",
        transition: {"type":"cut","dur":0},
        text: [
          {"t":7.8,"dur":8,"kind":"haiku","ja":["形見着て","祖母のかたちに","月を見る"],"author":"小夜","seal":"小夜","seal_style":"白文","zh":"披着她留下的念想——以祖母的身形，看月。","position":"right","x":1660,"y":120,"ink":"light","size":42},
        ],
      },
      {
        id: "fuji-no-keburi", title_ja: "結　不尽の煙", title_zh: "结　不尽之烟", duration: 30,
        shot: "E, then the unprinting",
        transition: {"type":"cut","dur":0},
        text: [
          {"t":1.3,"dur":6.7,"kind":"narration","ja":["その煙、いまだ雲の中へ","立ち昇るとぞ、言ひ伝へたる。"],"author":"竹取物語","seal":"月","seal_style":"朱文","zh":"据说，那烟至今仍向云中升腾。","position":"upper-left","x":120,"y":70,"ink":"dark","size":32},
          {"t":20.8,"dur":10.8,"kind":"haiku","ja":["影ひとつ","格子をのぼる","良夜かな"],"author":"小夜","seal":false,"zh":"一道影子，攀上窗格——好一个良宵。","position":"upper-right","x":1180,"y":170,"ink":"dark","size":52},
        ],
      },
    ],
  };
})(window.TSUKI = window.TSUKI || {});
