#!/usr/bin/env node
/* ==========================================================================
   tools/fonts.js — vendor subset web fonts.
   Scans every text the film can show (script, page, scenes) and downloads
   Google Fonts subsets that contain exactly those glyphs, so the film works
   offline, in single-file builds, and in headless capture.
     node tools/fonts.js
   Uses curl (honours the environment's proxy/CA settings).
   ========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'fonts');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const FAMILIES = [
  { family: 'Yuji Syuku', weights: [400], file: 'yuji-syuku' },
  { family: 'Shippori Mincho B1', weights: [400, 600, 800], file: 'shippori-b1' },
  { family: 'Noto Serif SC', weights: [400, 600], file: 'noto-serif-sc' },
];

function collectText() {
  const files = [
    'index.html', 'js/script.js', 'js/main.js', 'js/core/engine.js', 'js/core/brush.js',
    ...fs.readdirSync(path.join(ROOT, 'js/scenes')).filter((f) => f.endsWith('.js')).map((f) => 'js/scenes/' + f),
  ];
  let text = '';
  for (const f of files) {
    const p = path.join(ROOT, f);
    if (fs.existsSync(p)) text += fs.readFileSync(p, 'utf8');
  }
  // always-available glyphs: kana, punctuation, digits, latin
  for (let c = 0x3041; c <= 0x3096; c++) text += String.fromCodePoint(c);
  for (let c = 0x30a1; c <= 0x30fa; c++) text += String.fromCodePoint(c);
  text += 'ー・「」『』、。，．！？：；（）〜…―—　·×/0123456789';
  text += 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz .,:;!?\'"-()&';
  const set = new Set();
  for (const ch of text) {
    const cp = ch.codePointAt(0);
    if (cp < 0x20 || (cp >= 0xd800 && cp <= 0xdfff)) continue;
    set.add(ch);
  }
  return [...set].sort();
}

const curl = (url, out) => {
  const args = ['-sS', '--fail', '-A', UA, url];
  if (out) args.push('-o', out);
  return execFileSync('curl', args, { maxBuffer: 64 * 1024 * 1024 }).toString();
};

function chunks(chars, maxEncoded = 1800) {
  const out = [];
  let cur = [], len = 0;
  for (const ch of chars) {
    const e = encodeURIComponent(ch).length;
    if (len + e > maxEncoded && cur.length) { out.push(cur); cur = []; len = 0; }
    cur.push(ch); len += e;
  }
  if (cur.length) out.push(cur);
  return out;
}

function range(chars) {
  return chars.map((c) => 'U+' + c.codePointAt(0).toString(16).toUpperCase()).join(', ');
}

function main() {
  const chars = collectText();
  console.log(`${chars.length} distinct glyphs`);
  fs.mkdirSync(OUT, { recursive: true });
  for (const f of fs.readdirSync(OUT)) if (f.endsWith('.woff2') || f.endsWith('.ttf')) fs.unlinkSync(path.join(OUT, f));
  let css = '/* generated by tools/fonts.js — subset Google Fonts (SIL Open Font License) */\n';
  let bytes = 0;
  for (const fam of FAMILIES) {
    for (const w of fam.weights) {
      chunks(chars).forEach((part, i) => {
        const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(fam.family).replace(/%20/g, '+')}:wght@${w}&text=${encodeURIComponent(part.join(''))}`;
        let sheet;
        try { sheet = curl(url); } catch (e) { console.warn(`skip ${fam.family} ${w} #${i}: ${e.message.split('\n')[0]}`); return; }
        const m = sheet.match(/url\((https:[^)]+)\)\s*format\('([^']+)'\)/);
        if (!m) { console.warn(`no src for ${fam.family} ${w} #${i}`); return; }
        const ext = m[2] === 'woff2' ? 'woff2' : m[2] === 'truetype' ? 'ttf' : 'woff';
        const name = `${fam.file}-${w}-${i}.${ext}`;
        curl(m[1], path.join(OUT, name));
        bytes += fs.statSync(path.join(OUT, name)).size;
        css += `@font-face{font-family:'${fam.family}';font-style:normal;font-weight:${w};font-display:block;` +
          `src:url('${name}') format('${m[2]}');unicode-range:${range(part)};}\n`;
      });
    }
  }
  fs.writeFileSync(path.join(OUT, 'fonts.css'), css);
  console.log(`wrote fonts/fonts.css, ${(bytes / 1024).toFixed(0)} KiB of font data`);
}

main();
